language: python
python: 2.7
sudo: required
services: docker

install: true
script: true

env:
  global:
    - IMAGE_NAME=gabrielegiammatteo/fiware-monitoring-stack-ceilometer
    - REGISTRY_USER=gabrielegiammatteo
    # REGISTRY_PASS=...
    - secure: sWFtqNJeu7Y6/4rH9ZqoaAnAKjyriyhM4hRNPsEXO4CeEVrUhU+NfvIqvJnHiHE9byU9kCN0ij+1C0q3QWc+m1ajqOZFSXUbR4k0MCTyLC8pU36m+YEPsGYnmpoXYCInWmqzEmfgknuUf+s1mSETCf74X7Jf9qVzF/J/p6ZPSI2R76ZtYTTsXZlLUzNvdiRRQknvQmL262EFSPpjpNOjZwjtsV35amGVUmYDJshIg1nd/q5wPh25EUKYTxd4POa+nKfK6pDT5mAM31r4ireaHEkKmYeyosXyknyJaoU/nuUDTI/Y43Xap+d0Nyjh/UMO53iSFAKtz/lx1gFGF5Z5+XUsLbjUlYYqFYnHRhXXWlGsHykpW9KVjBUqIdy/rUk4W7JLH4e4T9n/EMrHK99OW3BOj4PqxU2pXJ5aMJzFZoPbLyK9LgP95TzgbXlwPQRw2w9ZeRYgmPaY5DU8fL69ZzVLrs39NvBhrRjmKXPDlhZucuuCHHZNI2GxdP/CMZaijoeU1yK6tQIIdCGCIHxNIk43L4Wy/78UJeSig7hQZXLmC0sJDyZucXO7y+ZGO70p10rUpcRZubiIbeWVAa7lya4NODQTs/3xNNSgnBCiydBc38q9nmMIJSDep7NjXMWHmZOExRHcC2F8P3VSRc6cxEeRWJHp7yOeLlB2WczuTjo=

before_deploy:
  - docker pull "${IMAGE_NAME}:develop" || true
  - docker build --pull --cache-from "${IMAGE_NAME}:develop" --tag "$IMAGE_NAME" fiprom_collector_service
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:develop"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:

  # publish Docker development image
  - provider: script
    script: docker push "${IMAGE_NAME}:develop"
    on:
      all_branches: true

  # publish Docker release image if it is a tag commit
  - provider: script
    script: docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
    on:
      tags: true

