version: "3"
services:

  collector_service:
    image: gabrielegiammatteo/fiware-monitoring-stack-ceilometer:develop
    env_file:
      - "${FIWARE_MON_CONFIG:-./}/config.env"
    environment:
      dispatcherUrl: http://fiprom:9099/