# inspired by https://github.com/vegasbrianc/prometheus

version: "3"
services:
  grafana:
    image: grafana/grafana:6.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
  prometheus:
    image: prom/prometheus:v2.8.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
 
  pushgateway:
    image: prom/pushgateway:v0.7.0
  
  fiprom:
    image: gabrielegiammatteo/fiware-prometheus-publisher:develop
    volumes:
      - "${FIWARE_MON_CONFIG:-./}/:/config/"

  prometheus-openstack-exporter:
    image: gabrielegiammatteo/prometheus-openstack-exporter:develop
    ports:
      - "9183:9183"
    env_file:
      - "${FIWARE_MON_CONFIG:-./}/poe.env"

volumes:
  grafana_data: {}
  prometheus_data: {}
