# inspired by https://github.com/vegasbrianc/prometheus

version: "3"
services:

  grafana-db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ${FIWARE_MON_SECURE:-secret}
      MYSQL_DATABASE: grafana
    volumes:
      - grafana_db:/var/lib/mysql

  grafana-web:
    image: grafana/grafana:6.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - "${FIWARE_MON_CONFIG:-./}/config.env"
    environment:
      GF_INSTALL_PLUGINS: grafana-worldmap-panel,neocat-cal-heatmap-panel,petrslavotinek-carpetplot-panel,digiapulssi-breadcrumb-panel,yesoreyeram-boomtable-panel,michaeldmoore-multistat-panel,grafana-piechart-panel,flant-statusmap-panel,vonage-status-panel,natel-discrete-panel,farski-blendstat-panel
      GF_DATABASE_URL: mysql://root:${FIWARE_MON_SECURE:-secret}@grafana-db:3306/grafana
      GF_SECURITY_ADMIN_PASSWORD: ${FIWARE_MON_SECURE:-secret}

  prometheus:
    image: prom/prometheus:v2.8.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=90d'


volumes:
  grafana_data:
  prometheus_data:
  grafana_db:
