{
 "title": "New dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Compute CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "os_compute_node_cpu_percent", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Network Incoming Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "os_network_incoming_bytes", "legendFormat": "{{instance}} ({{user}})" }
   ]
  },
  {
   "title": "CPU Util by host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(os_cpu_util) by (host_id)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "os_network_incoming_bytes_rate", "legendFormat": "{{instance}} ({{user}})" },
    {
     "expr": "- os_network_outgoing_bytes_rate",
     "legendFormat": "{{instance}} ({{user}})"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "os_cpu_util", "legendFormat": "{{instance}} ({{user}})" }
   ]
  },
  {
   "title": "Metrics Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "time() - push_time_seconds", "legendFormat": "{{resource_id}}" }
   ]
  }
 ]
}