{
 "title": "Instance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance_id", "label": "Instance Id", "query": "label_values(instance_id)" }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_instance{instance_id=\"$instance_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_instance{instance_id=\"$instance_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "os_cpu_util{instance_id=\"$instance_id\"}"
    }
   ]
  },
  {
   "title": "Memory Util",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "os_memory_usage{instance_id=\"$instance_id\"}"
    }
   ]
  }
 ]
}