{
 "title": "POE",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top 20 Unused CPU Quota",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, nova_quota_cores - ignoring(type) nova_resources_vcpus)"
    }
   ]
  },
  {
   "title": "Top 20 Unused Memory Quota",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, nova_quota_ram_mbs - ignoring(type) nova_resources_ram_mbs)"
    }
   ]
  },
  {
   "title": "Top 20 Unused Floating IP Quota",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 13, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, sum(nova_quota_floating_ips) by (tenant) - sum(neutron_public_ip_usage{ip_status=\"ACTIVE\"}) by (tenant))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(nova_quota_cores) by (tenant_group)",
     "legendFormat": "{{tenant_group}} | Quota"
    },
    {
     "expr": "sum(nova_resources_vcpus) by (tenant_group)",
     "legendFormat": "{{tenant_group}} | Used"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(nova_quota_cores) by (tenant_group)"
    },
    {
     "expr": "sum(nova_resources_vcpus) by (tenant_group)"
    }
   ]
  },
  {
   "title": "Unbound tenant",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(nova_instances{tenant_group=\"unknown\"}) by (tenant)"
    }
   ]
  }
 ]
}